### ISSUE TITLE
Realme GT Neo 2 (Bitra)

### ISSUE THREAD

**Issue by s1mpleog** [Matrixx-Devices/official_devices#11]
## Name and Codename of the device you want to apply for
```
Realme Gt Neo 2 5G(Bitra)
```

## Device Tree sources

```
https://github.com/s1mpleog/android_device_realme_bitra
https://github.com/s1mpleog/kernel_realme_sm8250
https://github.com/s1mpleog/android_vendor_realme_bitra
https://github.com/s1mpleog/android_device_realme_sm8250-common
```

## What ROM's do you maintain officially/unofficially
```
Pixel os, Pixel Experience and Cherish os (all unofficially)
```

## How long have you been building Custom ROMs
```
3 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
i build locally
```
## Free trial user or paid user?
```
i build locally
```

### Telegram username
@SimpleTheOG
Your Telegram username
```

### GitHub username
```
s1mpleog
```

### [MUST] Link to your XDA thread of unofficial build
<!-- Before being able to maintainer Project-Matrixx officially,
you must have already made an XDA
Refer Maintainer Requirements -->
```
https://xdaforums.com/t/project-matrixx-10-1-2-for-realme-gt-neo-2-bitra.4647770/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA
<!-- Before being able to maintainer Project-Matrixx officially,
you must have already made your unofficial build public.
Refer Maintainer Requirements -->
```
https://t.me/RealmeGTNeo2_Official/458434
https://t.me/simpleprojectss/1442
```

**Comment by mukesh22584** [comment]
Please learn properly How to handle/use git
