### ISSUE TITLE
Want to apply for Official maintainership of Project matrixx for Redmi note 7 pro aka Violet

### ISSUE THREAD

**Issue by CuriousNom** [Matrixx-Devices/official_devices#12]
## Name and Codename of the device you want to apply for
Redmi Note 7 Pro (violet)
## Device Tree sources

https://github.com/CuriousNom/chaste_device_xiaomi_violet.git
https://github.com/CuriousNom/chaste_kernel_xiaomi_violet.git
https://github.com/CuriousNom/chaste_vendor_xiaomi_violet.git
## What ROM's do you maintain officially/unofficially
Maintain Project Blaze Unofficial only
## How long have you been building Custom ROMs
2 months
## Do you build locally or rely on server if server what cloud service provider do you use ?
I Build locally on my pc but will buy a server when necessary
## Free trial user or paid user?
none
### Telegram username
@The_Riderrr
### GitHub username
CuriousNom
### [MUST] Link to your XDA thread of unofficial build

Thread '[ROM][U][Violet] Project Matrixxx [UNOFFICIAL]' https://xdaforums.com/t/rom-u-violet-project-matrixxx-unofficial.4647890/
### [MUST] Link to your unofficial Matrixx Build Post other than XDA

https://t.me/RomCentralHub/409

**Comment by Mrick343** [comment]
Your trees don't meet out the expectation of being officially supported. Kindly learn git stuff and fix ur commit history. 
After gaining some more experience, you can come back and try again
