### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by IczYn** [Matrixx-Devices/official_devices#14]
## Name and Codename of the device you want to apply for
```
Motorola G82 5G (Rhodep)
```

## Device Tree sources
I use common tree for all motorola`s devices.
https://github.com/orgs/moto-common/repositories
but i fork trees to my github for chagne some staff
https://github.com/IczYn/android_kernel_motorola_msm-5.4
https://github.com/IczYn/android_device_motorola_rhodep/tree/a14

## What ROM's do you maintain officially/unofficially
```
in new community i start make matrixx and cherish 
old phone i make only matrixx
```

## How long have you been building Custom ROMs
```
something like 10 month 
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
i rent server on private(monthly rent) fast server a14 build 1,5h ;)
```
## Free trial user or paid user?
```
free?? idk
```

### Telegram username
```
https://t.me/IczYn
```

### GitHub username
```
https://github.com/IczYn
```

### [MUST] Link to your XDA thread of unofficial build

```
our community dont use XDA. 
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/G82Updates/26 - this post is before we fix fast charge and video recording
https://t.me/thechimestuff/2073 - old phone community

```

**Comment by Mrick343** [comment]
Accepted
