### ISSUE TITLE
Maintainer for realme 9 5G SE

### ISSUE THREAD

**Issue by arteryring** [Matrixx-Devices/official_devices#17]
## Name and Codename of the device you want to apply for
```
realme 9 5G SE (ice)
```

## Device Tree sources

```
https://github.com/orgs/matrixx-ice/repositories
```

## What ROM's do you maintain officially/unofficially
```
I maintain matrixx-os and pixelos unofficialy
```

## How long have you been building Custom ROMs
```
1.5 years
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally
```
## Free trial user or paid user?
```
I build locally.
```

### Telegram username
```
@arteryring1
```

### GitHub username
```
arteryring
```

### [MUST] Link to your XDA thread of unofficial build

```
https://t.me/sidharthgarage/51
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/Realme9SE_Official/155317
https://t.me/sidharthgarage/51

```

**Comment by mukesh22584** [comment]
Please read criteria to apply maintainership. Please learn how to cherry-pick.

**Comment by arteryring** [comment]
I read the criteria, also some commits don't have authorship because I sadly couldn't find the original commit for those changes

**Comment by mukesh22584** [comment]
> I read the criteria, also some commits don't have authorship because I sadly couldn't find the original commit for those changes

Link me any single commit that you have cherry-picked ?

**Comment by arteryring** [comment]
I cherry picked some commits on the vendor repo on my older account (which is flagged, thats why this account is new)

However if you still doubt me, it's fine. I'll make my history cleaner and remind you :)
