### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Pyrtle93** [Matrixx-Devices/official_devices#18]
## Name and Codename of the device you want to apply for
```
Your device name (Your device codename)
``` Pixel 7 - Panther
    Pixel 7 Pro - Cheetah

## Device Tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```
https://github.com/Pyrtle93/android_device_google_pantah - branch 14
https://github.com/Pyrtle93/android_device_google_gs201.git - branch 14
https://github.com/Pyrtle93/proprietary_vendor_google_cheetah - branch 14
https://github.com/Pyrtle93/Kirisakura_Pantah - branch pantah
https://github.com/Pyrtle93/vendor_pixel-framework/tree/14 - branch 14
```

## What ROM's do you maintain officially/unofficially
```
Ancient offically
```

## How long have you been building Custom ROMs
```
4-5 years
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Server with Jenkins access
```
## Free trial user or paid user?
```
Paid
```

## Contact

### Telegram
@Pyrtle93

### GitHub username
```
Pyrtle93
```

### [MUST] Link to your XDA thread of unofficial build
<!-- Before being able to maintainer Project-Matrixx officially,
you must have already made an XDA
Refer Maintainer Requirements -->
```
Link to where you have posted your build publically.    I haven't made an unofficial XDA post yet
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA
<!-- Before being able to maintainer Project-Matrixx officially,
you must have already made your unofficial build public.
Refer Maintainer Requirements -->
```
Link to where you have posted your build publically.

https://t.me/PyrtlesPixels

**Comment by mukesh22584** [comment]
Approved 👍
