### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by GokuSan2** [Matrixx-Devices/official_devices#22]
## Name and Codename of the device you want to apply for
```
Sweet/sweetin
```

## Device Tree sources

```
https://github.com/kamleshhv/device_xiaomi_sweet/tree/matrixx
https://github.com/kamleshhv/device_xiaomi_sm6150-common/tree/matrixx
https://github.com/kamleshhv/kernel_xiaomi_sm6150
https://github.com/kamleshhv/vendor_xiaomi_sweet
https://github.com/kamleshhv/vendor_xiaomi_sm6150-common
```

## What ROM's do you maintain officially/unofficially
```
Project blaze official
Alphadroid unofficial 
```

## How long have you been building Custom ROMs
```
6 month
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Server
```
## Free trial user or paid user?
```
Paid
```

### Telegram username
```
@kamleshpatidar
```

### GitHub username
```
@kamleshhv
```

### [MUST] Link to your XDA thread of unofficial build

```
Not upload on xda forum 
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/RedmiNote10ProChannel/2020
```

**Comment by mukesh22584** [comment]
Thanks for interest and No official because no XDA.
