### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by DeandraAir** [Matrixx-Devices/official_devices#26]
## Name and Codename of the device you want to apply for
```
Redmi Note 10 (mojito/sunny)
```

## Device Tree sources

```
https://github.com/DeandraAir/device_xiaomi_mojito-14
https://github.com/DeandraAir/kernel_xiaomi_mojito-14
https://github.com/DeandraAir/vendor_xiaomi_mojito-14
```

## What ROM's do you maintain officially/unofficially
```
Alpha Droid/CherishOS/EvolutionX/Matrixx/AwakenOS/Derpfest/LeafOS/DroidX/Superior Extended/ColtOS/SparkOS (UnOfficialy)
```

## How long have you been building Custom ROMs
```
7 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
server (Azure Microsoft)
```
## Free trial user or paid user?
```
paid
```

### Telegram username
```
@DeanPerformer
```

### GitHub username
```
DeandraAir
```

### [MUST] Link to your XDA thread of unofficial build

```
Link to where you have posted your build publically.
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/RedmiNote10IDUpdate/1492
https://t.me/RedmiNote10ID/782466
https://sourceforge.net/projects/premiumprjktrom/files/Mojito/Android14/
```

**Comment by mukesh22584** [comment]
I'm not seeing any commit that you have cherry-picked. Another thing is, "Please don't ask if you can't fulfill all maintainership requirements."
[**Check Here**]( https://github.com/Matrixx-Devices/official_devices/blob/14.0/README.md)
