### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by MNoxx74** [Matrixx-Devices/official_devices#27]
## Name and Codename of the device you want to apply for
```
Realme GT 5G (RMX2202L1,cupidr)
```
Your device name (Your device codename)
```
cupidr
```

## Device Tree sources

```
https://github.com/realme-GT-A14-Development/android_device_realme_cupidr.git

https://github.com/realme-GT-A14-Development/android_kernel_oneplus_sm8350.git

https://github.com/realme-GT-A14-Development/vendor_realme_cupidr
```

## What ROM's do you maintain officially/unofficially
```
Evolution x ,CherishOS, ArrowOS tequilaOS (unofficial)
```

## How long have you been building Custom ROMs
```
2-3 years
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
My PC
```

### Telegram username
```
https://t.me/MNoxx74
```

### GitHub username
```
https://github.com/MNoxx74
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/m/mnoxx74.11750893/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/RealmeGT_Official/57127
```

**Comment by mukesh22584** [comment]
Everything looks good But XDA thread is must. 
Follow [**HERE**](https://github.com/Matrixx-Devices/official_devices/blob/14.0/README.md)
