### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by 47lucid** [Matrixx-Devices/official_devices#29]
## Name and Codename of the device you want to apply for
```
Realme 6/6i(Indian)/6s/7/Narzo 20 Pro/Narzo 30 4G (Code Name: RM6785)
```

## Device Tree sources
```
Device Tree
https://github.com/realme-mt6785-devs/android_device_realme_RMX2001L1.git

Common Device Tree

https://github.com/realme-mt6785-devs/android_device_realme_RM6785-common.git

Vendor Tree

https://github.com/realme-mt6785-devs/proprietary_vendor_realme_RM6785-common.git

Kernel Tree

https://github.com/realme-mt6785-devs/android_kernel_realme_mt6785.git

```

## What ROM's do you maintain officially/unofficially
```
unofficially
-GenesisOS
-ApolloOS
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Building Locally
```

### Telegram username
```
@WaitinnForUhh
```

### GitHub username
```
47lucid
```

### [MUST] Link to your unofficial Build Post
```

https://t.me/RM6Official

https://t.me/lucid_builds

```

**Comment by Mrick343** [comment]
Please fill the form properly.. There's no xda link for your build. XDA thread is manadatory and how long you have been in rom development is also necessary. You will not get accepted until and unless everything is done according to the rules given [here](https://github.com/Matrixx-Devices/official_devices/blob/14.0/README.md)
