### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by troublescope** [Matrixx-Devices/official_devices#30]

**Comment by kssrao13882** [comment]
Thanks for showing your interest in official maintainership.

Check this commit once
https://github.com/AndroDesk/android_device_xiaomi_rosemary/commit/36ef9fb4bc2820e5a87d26690acf9a2f22415ea2

In smart pixels commit, u have added proximity check code too.

And why is there no file in download link given in xda? 

The team feels your contribution to dt can be even more.

Probably correct the commit, contribute more to DT and Better luck next time.
