### ISSUE TITLE
New maintainer Samsung Galaxy Tab S6 Lite 2020 wifi

### ISSUE THREAD

**Issue by Jrcable1** [Matrixx-Devices/official_devices#33]
## Name and Codename of the device you want to apply for
```
Your device name (Your device codename)
```
Samsung Galaxy Tab S6 Lite 2020 WiFi 
(gta4xlwifi)
## Device Tree sources
 https://github.com/Jrcable1
```
https://github.com/Jrcable1/android_device_samsung_gta4xlwifi
https://github.com/Jrcable1/android_kernel_samsung_gta4xl
https://github.com/Jrcable1/android_vendor_samsung_gta4xlwifi
```

## What ROM's do you maintain officially/unofficially
```
Insert here
``` 
Rising for Pixel 6 Pro(unofficial)
Matrixx for gta4xlwifi (unofficial)
Matrixx for Pixel 6 pro (personal builds)

## How long have you been building Custom ROMs
```
Insert here
```
off and on for years. Build personal Resurrection Remix for Nexus 6/6p back in the day. Came back in April 2023

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Insert here
``` 
Locally
## Free trial user or paid user?
```
Insert here
```

### Telegram username
```
Your Telegram username
``` 
Jrcable2

### GitHub username
```
Your Github username
``` 
Jrcable1

### [MUST] Link to your XDA thread of unofficial build

```
Link to where you have posted your build publically.
``` 
https://xdaforums.com/t/a14-rom-project-matrixx-v10-3-gta4xlwifi-unofficial.4659165/#post-89371650
https://xdaforums.com/t/project-matrixx-rom.4656136/#post-89370004

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
Link to where you have posted your build publically.
``` 
https://drive.google.com/drive/folders/1woN9B5nLstKJEpE0ma6_5setoGvYP9-g

**Comment by Jrcable1** [comment]
I try my best to keep my trees clean and simple, with no useless, overlapping, broken and incorrect commits. My build runs, runs good with no device side issues.

**Comment by Mrick343** [comment]
okay...I'm closing your issue and Your application is accepted.. Please contact @AAMIRR_ALI in telegram for your joining in groups and getting access..
