### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Cristianlp2** [Matrixx-Devices/official_devices#35]
## Name and Codename of the device you want to apply for
```
Xiaomi 11t pro Vili 
```

## Device Tree sources

```
https://github.com/Cristianlp2/device-vili
https://github.com/Cristianlp2/android_device_xiaomi_sm8350-common-new
https://github.com/Cristianlp2/proprietary_vendor_xiaomi_sm8350-common
https://github.com/Cristianlp2/proprietary_vendor_xiaomi_vili
https://github.com/Cristianlp2/kernel_vili
```

## What ROM's do you maintain officially/unofficially
```
Alphadroid official , Rising unofficial
```

## How long have you been building Custom ROMs
```
4 Years
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally
```
## Free trial user or paid user?
```
Insert here
```

### Telegram username
```
@Cr1st1anlp
```

### GitHub username
```
Cristianlp2
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-a14-vili-project-matrixx-10-3-0-unofficial.4660470/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/LpVili/336
```

**Comment by kssrao13882** [comment]
Where is Matrixx stuff in DT like battery info, display info etc.? U have only one branch in ur DT and that's of AlphaDroid

**Comment by Cristianlp2** [comment]
Sorry my mistake is already fixed

**Comment by kssrao13882** [comment]
Congrats u are in. Check ur telegram for further formalities
