### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AswinOP** [Matrixx-Devices/official_devices#4]
## Name and Codename of the device you want to apply for
```
POCO X4 Pro 5G/Redmi Note 11 Pro+ 5G (VEUX/PEUX)
```

## Device Tree sources

```
https://github.com/AswinOP/device_xiaomi_veux
https://github.com/crdroidandroid/android_kernel_oneplus_sm8350
https://gitlab.com/JaswalAshish/vendor_xiaomi_veux 
```

## What ROM's do you maintain officially/unofficially
```
crDroid, ProjectMatrixx, PixelOS
```

## How long have you been building Custom ROMs
```
Since November 4/'23
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No (since a14 is still not stable yet i don't want to mess with sources for now)
```

### Telegram username
```
iaswinop
```

### Link to your XDA thread of unofficial build

```
XDA - https://xdaforums.com/t/rom-a14-project-matrixx-10-0-beta-2-unofficial.4642613/
```

### Link to your unofficial Build Post other than XDA

```
SourceForge - https://sourceforge.net/u/aswinop/profile/
```

**Comment by Mrick343** [comment]
Brother your Device trees is not clear. You had pushed all things all together. You need to fix your device tree.

**Comment by Mrick343** [comment]
I'm closing your request as your device tree is not clear. You can come back later after you gain some experience and a well maintained  device tree.

**Comment by AswinOP** [comment]
> I'm closing your request as your device tree is not clear. You can come back later after you gain some experience and a well maintained device tree.

Yep i can understand, will be better when you see them next time :) have a good day sar <3

**Comment by Mrick343** [comment]
Okay
