### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by MNoxx74** [Matrixx-Devices/official_devices#44]
## Name and Codename of the device you want to apply for
```
Realme GT 5G (cupidr)
```

## Device Tree sources

```
https://github.com/realme-GT-A14-Development/android_device_realme_cupidr/commits/lineage-21.0/
https://github.com/realme-GT-A14-Development/android_device_oneplus_sm8350-common/commits/lineage-21/
https://github.com/realme-GT-A14-Development/android_kernel_oneplus_sm8350/commits/lineage-21.0/
https://github.com/MNoxx74/vendor_realme_cupidr
https://github.com/MNoxx74/proprietary_vendor_oneplus_sm8350-common
```

## What ROM's do you maintain officially/unofficially
```
Pixelstar official , GenesisOS unofficial , Project Matrixx unofficial
```

## How long have you been building Custom ROMs
```
2-3 years 
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
locally 
```
## Free trial user or paid user?
```
Insert here
```

### Telegram username
```
https://t.me/MNoxx74
```

### GitHub username
```
https://github.com/MNoxx74
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/a14-rom-project-matrixx-v10-2-1-cupidr-unofficial.4659769/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/realmeGTnews_updates/69
```

**Comment by Mrick343** [comment]
Greetings from Team Matrixx,

We are happy to inform you that your application for Official Maintainership is accepted. Please contact @AAMIRR_ALI for invite link to Maintainers team and other formalities
