### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Arman-ATI** [Matrixx-Devices/official_devices#46]
## Name and Codename of the device you want to apply for
```
Oneplus 10 Pro (wly)
```

## Device Tree sources

```
https://github.com/ATI-labs/android_device_oneplus_wly/commits/matrixx/
https://github.com/ATI-labs/android_device_oneplus_sm8450-common/commits/matrixx/
https://github.com/Arman-ATI/android_kernel_oneplus_sm8450/commits/staging/lineage-20-no-ksu/
https://github.com/Arman-ATI/vendor_oneplus_wly/commits/lineage-21/
https://github.com/Arman-ATI/vendor_oneplus_sm8450-common/commits/OP-no-dolby/
https://github.com/ATI-labs/android_hardware_oplus/commits/matrixx/
```

## What ROM's do you maintain officially/unofficially
```
matrixx (unofficial) EvoX (unofficial)
```

## How long have you been building Custom ROMs
```
5 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
local
```
## Free trial user or paid user?
```
local
```

### Telegram username
```
@Arman_ATI
```

### GitHub username
```
Arman-ATI
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-unofficial-matrixx-v10-3-1-18-03-2024.4662723/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/Machad3xROMS/15720
```

**Comment by kssrao13882** [comment]
On going through your trees, it is observed that you need  better knowledge of git.

For instance to remove dolby, instead of deleting everything in a single commit, u r removing each file individually as a single commit. U have done same with updating the kernel modules as well. 

So better learn git and then plan to apply for official. As of now we can't take you into the team as official maintainer. Happy learning.

**Comment by Arman-ATI** [comment]
Hi sir,
thanks for letting me know the problem
Will definitely better my knowledge and then request

**Comment by Arman-ATI** [comment]
greetings! @kssrao13882
I just fixed my repos and cleaned up my commits!
please check out them!

https://github.com/ATI-labs/android_device_oneplus_wly/commits/matrixx/
https://github.com/ATI-labs/android_device_oneplus_sm8450-common/commits/matrixx-new/
https://github.com/Arman-ATI/android_kernel_oneplus_sm8450/commits/staging/lineage-20-no-ksu/
https://github.com/Arman-ATI/vendor_oneplus_wly/commits/lineage-21/
https://github.com/Arman-ATI/vendor_oneplus_sm8450-common/commits/OP-test/
https://github.com/ATI-labs/android_hardware_oplus/commits/matrixx/
