### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RiteshSahany** [Matrixx-Devices/official_devices#48]
## Name and Codename of the device you want to apply for
```
Redmi Note 9s/9 Pro India/10 Lite - (Curtana)
Redmi Note 9Pro Global - (Joyeuse)
Redmi Note 9Pro Max India - (Excalibur)
POCO M2 Pro - (Gram)
Unified Code Name - **Miatoll**
```

## Device Tree sources

```
https://github.com/ULTIMATE-RITESH/device_xiaomi_miatoll
https://github.com/ULTIMATE-RITESH/kernel_xiaomi_sm6250
https://github.com/ULTIMATE-RITESH/vendor_xiaomi_miatoll
```

## What ROM's do you maintain officially/unofficially
```
Evolution-X (unofficiall)
CherishOS (unofficiall)
Project-Matrixx (unofficiall)
```

## How long have you been building Custom ROMs
```
4 Months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
I rely on server (Google Cloud Platform)
```

## Free trial user or paid user?
```
Paid
```

### Telegram username
```
@RITESHROKX
```

### GitHub username
```
ULTIMATE-RITESH
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-0-miatoll-project-matrixx-unofficial-stable-aosp.4666538/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/Riteshroms
```

**Comment by kssrao13882** [comment]
U have mentioned u do three roms, but ur channel shows u also do roms like VoltageOS, horizondroid, genesis, tequila, waveos, parasite, crdroid, lmodroid, evox too.

So many roms? We don't see u fitting as official maintainer for Matrixx.

**Comment by ULTIMATE-RITESH** [comment]
Sorry sir, you got wrong impression of me as a buildbot...
I was building every rom for once to see which rom users liked the most. I
checked that in March update so I decided to only maintain Evolution-X,
CherishOS and Project-Matrixx for April update...
You can also see my chats in my support group that after posting matrixx I
said no more further updates for April Patch...
Also I once replied to another person who misunderstood me as a buildbot in
miatoll community, you can see here: https://t.me/MiatollOfficial/1467211

**Comment by kssrao13882** [comment]
> Sorry sir, you got wrong impression of me as a buildbot... I was building every rom for once to see which rom users liked the most. I checked that in March update so I decided to only maintain Evolution-X, CherishOS and Project-Matrixx for April update... You can also see my chats in my support group that after posting matrixx I said no more further updates for April Patch... Also I once replied to another person who misunderstood me as a buildbot in miatoll community, you can see here: https://t.me/MiatollOfficial/1467211
> […](#)
> Message ID: ***@***.*** com>

Sorry but team isn't convinced with this. Opinion of users can be simply sought through a poll instead of build and release 15+ different roms in a month. Better try after few months. For now, v can't take u in.
