### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by alecchangod** [Matrixx-Devices/official_devices#49]
## Name and Codename of the device you want to apply for
```
Mi 10 Lite 5G (monet)
```

## Device Tree sources

```
default branch(lineage-21-reb)
(Some old branch was kept for a reference, can remove them if needed)
https://github.com/alecchangod/android_device_xiaomi_monet
https://github.com/alecchangod/android_device_xiaomi_sm7250-common
https://github.com/alecchangod/kernel_xiaomi_sm7250
https://github.com/alecchangod/android_vendor_xiaomi
```

## What ROM's do you maintain officially/unofficially
```
All unofficial
LineageOS 21
Crdroid 10.4
Project matrixx 10.4.1
```

## How long have you been building Custom ROMs
```
About 16 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally 
```
## Free trial user or paid user?
```
N/A
```

### Telegram username
```
@alecchangod
```

### GitHub username
```
alecchangod
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-unofficial-monet-project-matrixx-android-14.4666666/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/mi10litereleases/508
```

**Comment by Mrick343** [comment]
Greetings from Team Matrixx,

We are happy to inform you that your application for Official Maintainership is accepted. Please contact @AAMIRR_ALI for invite link to Maintainers team and other formalities
