### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by shoya0x00** [Matrixx-Devices/official_devices#53]
## Name and Codename of the device you want to apply for
```
Poco X3 NFC (surya)
```
## Device Tree sources

```
https://github.com/surya-aosp/device_xiaomi_surya/tree/matrixx
https://github.com/surya-aosp/arise_xiaomi_surya/tree/surya
https://github.com/surya-aosp/vendor_xiaomi_surya/tree/aosp
```
## What ROM's do you maintain officially/unofficially
```
Official:
Project Blaze -> @shoya0x00
Superior Extended -> @Muichiro09

Unofficial:
PixysOS -> @shoya0x00
Project Awaken -> @Muichiro09
```

## How long have you been building Custom ROMs
```
I am building for 2 month.
Co-maintainer building for more than 1 year
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Usually build using azure server. Got local server and PC capable of building
```
## Free trial user or paid user?
```
Currently Paid.
```

### Telegram username
```
@lily985 
@Muichi09
```

### GitHub username
```
@shoya0x00
@Muichiro09
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-a14-xiaomi-poco-x3-nfc-matrixx-v10-4-1-gapps-vanilla-04-24-2024.4668629/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/pocox3build/81
```

**Comment by kssrao13882** [comment]
Ur telegram channel shows u released elixir and derpfest too this April and there are ss of rising. What about these roms. So is it 4 mentioned in form in addition to these 3 plus Matrixx u guys doing?

If that's the case, sorry official Matrixx is not for u guys.

**Comment by shoya0x00** [comment]
> Ur telegram channel shows u released elixir and derpfest too this April and there are ss of rising. What about these roms. So is it 4 mentioned in form in addition to these 3 plus Matrixx u guys doing?
> 
> If that's the case, sorry official Matrixx is not for u guys.

Yes I posted about those. I applied for elixir. They asked for test build so I posted. Derp build was only to test qpr2 tree. I was getting bootloop because of kernel. And about the rising os it was just test build. before I was building Matrixx I got bootloop I thought about bpf issue. Once I messaged about in matrixx group. But I was wrong so test builded rising not posted build.


If You got any other questions then let me know. I am currently maintaining 2. Total 3 with Project Matrixx.

**Comment by shoya0x00** [comment]
Also we will be co-maintaining currently only 1. Project Matrixx. Rest of those mentioned in the form we maintain individually. and we did build some of the rom to test a14 qpr2 tree and kernel patch.

**Comment by Mrick343** [comment]
So You applying for both of you

**Comment by shoya0x00** [comment]
> So You applying for both of you
> 
> 

Yes I am it seems like I am applying for both of us. If not possible for co-maintain approval then you guys can just give one of us official maintainer. We would still be happy with that.

**Comment by shoya0x00** [comment]
I would be actively building and we both will be actively improving dt and do bug fixes

**Comment by kssrao13882** [comment]
> > Ur telegram channel shows u released elixir and derpfest too this April and there are ss of rising. What about these roms. So is it 4 mentioned in form in addition to these 3 plus Matrixx u guys doing?
> > If that's the case, sorry official Matrixx is not for u guys.
> 
> Yes I posted about those. I applied for elixir. They asked for test build so I posted. Derp build was only to test qpr2 tree. I was getting bootloop because of kernel. And about the rising os it was just test build. before I was building Matrixx I got bootloop I thought about bpf issue. Once I messaged about in matrixx group. But I was wrong so test builded rising not posted build.
> 
> If You got any other questions then let me know. I am currently maintaining 2. Total 3 with Project Matrixx.

What about elixir official that u applied for?

**Comment by kssrao13882** [comment]
Congrats u guys are in. U can comaintain. Check tg for further formalities

**Comment by shoya0x00** [comment]
> What about elixir official that u applied for?

Status of the elixir is unknown. No reply from them. Maybe waitlisted. They will add in future. No idea what they are thinking. They don't reply to pm. One of my friend asked about update in their community they give them warn.
