### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by cat658011** [Matrixx-Devices/official_devices#54]
## Name and Codename of the device you want to apply for
```
Samsung Galaxy A51 (a51 or a515f)
```

## Device Tree sources

```
https://github.com/Exynos9611Development/android_device_samsung_universal9611-common
https://github.com/Exynos9611Development/android_device_samsung_a51
https://github.com/Exynos9611Development/android_vendor_samsung_universal9611-common
https://github.com/Exynos9611Development/android_vendor_samsung_a51
```

## What ROM's do you maintain officially/unofficially
```
LOS 21 - UNOFFICIAL
crDroid - UNOFFICIAL
```

## How long have you been building Custom ROMs
```
8 weeks
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
i build locally
```
## Free trial user or paid user?
```
free
```

### Telegram username
```
@Cat65801
```

### GitHub username
```
cat658011
```

**Comment by kssrao13882** [comment]
Where is the link to unofficial build released in xda and telegram channel? Why even remove certain fields from form that are clearly marked as MUST.
