### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by artemscine** [Matrixx-Devices/official_devices#55]
## Name and Codename of the device you want to apply for
```
Redmi Note 12 4G (topaz/tapas)
```

## Device Tree sources

```
https://github.com/NPDTeam/device_xiaomi_topaz-old
https://gitlab.com/nikita-prjkts/device_xiaomi_topaz-kernel/-/tree/14.0
https://github.com/NPDTeam/vendor_xiaomi_topaz-old
```

## What ROM's do you maintain officially/unofficially
```
Publicly - none, only Matrixx
```

## How long have you been building Custom ROMs
```
6 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
locally
```
## Free trial user or paid user?
```
building locally
```

### Telegram username
```
@onlyscine
```

### GitHub username
```
artemscine
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-unofficial-gapps-project-matrixx-10-4-3-for-redmi-note-12-4g.4669599/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/NPDTeam/8852/13155
https://t.me/RedmiNote12Indonesia_ch/261
https://t.me/RN124GTAPAS/444
```

**Comment by Mrick343** [comment]
Greetings from Team Matrixx,

We are happy to inform you that your application for Official Maintainership is accepted. Please contact @AAMIRR_ALI for invite link to Maintainers team and other formalities
