### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by YagizErdemir06** [Matrixx-Devices/official_devices#56]
## Name and Codename of the device you want to apply for
```
Redmi Note 12 Pro 5G (Ruby)
```

## Device Tree sources

```
https://github.com/Allien10X/android_device_xiaomi_ruby
https://github.com/Allien10X/android_vendor_xiaomi_ruby
https://github.com/Allien10X/android_kernel_xiaomi_mt6877
```

## What ROM's do you maintain officially/unofficially
```
I am currently using the unofficial project matrix I made myself.
```

## How long have you been building Custom ROMs
```
I've been making these roms for about 4 months and I'm improving every day.
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Microsoft Azure
```
## Free trial user or paid user?
```
I am currently using a free trial, but I will pay when I get maintainer.
```

### Telegram username
```
travisexe
```

### GitHub username
```
Allien10X
```

### [MUST] Link to your XDA thread of unofficial build

```
https://t.me/RubyTravis
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://sourceforge.net/projects/roms-garbages/files/Roms/Ruby/Matrixx10.4.3-MiuiCamera/
https://t.me/RedmiNote12ProPlusUpdates/62
```

**Comment by kssrao13882** [comment]
The questions was which roms u maintain, u say u use Matrixx u made. What other roms u maintain?

**Comment by kssrao13882** [comment]
Upon going through your trees, v feel u need to learn git better. Single commit isn't the way of making official roms. May be in the future Make trees better and reapply.

**Comment by YagizErdemir06** [comment]
Currently the tree is the latest version and I am updating it. Since you want a clean repository, I deleted the repository and reinstalled it clean.

**Comment by YagizErdemir06** [comment]
I deleted them all and uploaded them to a new repository from scratch. I already know Git and commits, I'm working on this device.

**Comment by kssrao13882** [comment]
> I deleted them all and uploaded them to a new repository from scratch. I already know Git and commits, I'm working on this device.

Single commit isn't the way bro. Proper commits with authorship and commit history is must
