### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RiteshSahany** [Matrixx-Devices/official_devices#57]
## Name and Codename of the device you want to apply for
```
Redmi Note 9s/9 Pro/Max/10 Lite/Poco M2 Pro (miatoll)
```

## Device Tree sources

```
https://github.com/ULTIMATE-RITESH/device_xiaomi_miatoll
https://github.com/ULTIMATE-RITESH/kernel_xiaomi_sm6250
https://github.com/ULTIMATE-RITESH/vendor_xiaomi_miatoll
```

## What ROM's do you maintain officially/unofficially
```
CherishOS (officiall)
Evolution-X (unofficiall)
Project-Matrixx (unofficiall)
```

## How long have you been building Custom ROMs
```
5 Months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Server (Google Cloud Platform)
```
## Free trial user or paid user?
```
Paid
```

### Telegram username
```
@RITESHROKX
```

### GitHub username
```
ULTIMATE-RITESH
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-0-miatoll-project-matrixx-unofficial-stable-aosp.4666538/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/Riteshroms
```

**Comment by kssrao13882** [comment]
U were told to apply after few months, not immediately the next month. And u r applying with trees showing cherish bringup for Matrixx. 🙄

Pls don't re-apply for Matrixx official maintainership henceforth

**Comment by RiteshSahany** [comment]
I can do the bringup part for Matrixx... I thought you wanted to see if the trees are maintained in a tidy and organized manner.
Also to check proper original commit authorship is maintained or not.
I like Matrixx rom that's why I was very eager to maintain it officially. Also I didn't build any ROM's except for those mentioned above.
