### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Machad3x** [Matrixx-Devices/official_devices#58]
## Name and Codename of the device you want to apply for
```
Oneplus 10 Pro (wly) and Realme GT 2 Pro (ferrarri)
```

## Device Tree sources

```
https://github.com/Machad3x/android_device_oneplus_wly
https://github.com/Machad3x/android_device_realme_ferrarri

https://github.com/Machad3x/android_device_oneplus_sm8450-common

https://github.com/Machad3x/android_hardware_oplus

https://github.com/Machad3x/android_kernel_oneplus_sm8450
https://github.com/Machad3x/android_kernel_oneplus_sm8450-modules
https://github.com/Machad3x/android_kernel_oneplus_sm8450-devicetrees

https://github.com/Machad3x/proprietary_vendor_oneplus_sm8450-common
https://github.com/Machad3x/proprietary_vendor_oneplus_wly
https://gitlab.com/Machad3x/proprietary_vendor_realme_ferrarri
```

## What ROM's do you maintain officially/unofficially
```
Matrixx and PixelOS
```

## How long have you been building Custom ROMs
```
6 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally
```
## Free trial user or paid user?
```
Free
```

### Telegram username
```
Machad3x
```

### GitHub username
```
Machad3x
```

### [MUST] Link to your XDA thread of unofficial build

```
(outdated)
https://xdaforums.com/t/rom-a14-unofficial-matrixx-v10-2-1-gapps-21-01-2024.4651814/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/Machad3xROMS
```

**Comment by kssrao13882** [comment]
Any specific reason behind dropping support for gapps build and going with only vanilla build releases?

**Comment by Machad3x** [comment]
> Any specific reason behind dropping support for gapps build and going with only vanilla build releases?

I've decided to give the option from user decide which gapps to use.

**Comment by kssrao13882** [comment]
> > Any specific reason behind dropping support for gapps build and going with only vanilla build releases?
> 
> I've decided to give the option from user decide which gapps to use.

Usually v release both gapps and vanilla builds or just gapps builds in Matrixx. Not everyone is OK with just vanilla builds. So rethink on it. We don't allow official device with vanilla release alone. Moreover v don't ship all Google shit in Matrixx, its already very minimal gapps that v ship

**Comment by Machad3x** [comment]
> > > Any specific reason behind dropping support for gapps build and going with only vanilla build releases?
> > 
> > 
> > I've decided to give the option from user decide which gapps to use.
> 
> Usually v release both gapps and vanilla builds or just gapps builds in Matrixx. Not everyone is OK with just vanilla builds. So rethink on it. We don't allow official device with vanilla release alone. Moreover v don't ship all Google shit in Matrixx, its already very minimal gapps that v ship

I agree with that, but i'm trying to apply 2 devices, will take time building both variants. Users still have the option to install an minimal or full gapps, even not installing gapps.

If both variants is must, i'm interested to know If exist any flag to easyly build both variants.

**Comment by kssrao13882** [comment]
Sorry to inform you that team feels you are not suitable as official maintainer for now.
