### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by JoseMCCGit** [Matrixx-Devices/official_devices#60]
## Name and Codename of the device you want to apply for
```
Motorola Edge 30 (dubai)
```

## Device Tree sources

```
https://github.com/JoseMCCGit/android_device_motorola_dubai
https://github.com/JoseMCCGit/android_kernel_motorola_sm7325
https://github.com/JoseMCCGit/android_vendor_motorola_dubai
```

## What ROM's do you maintain officially/unofficially
```
Project Matrixx
```

## How long have you been building Custom ROMs
```
6 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally
```
## Free trial user or paid user?
```
Free
```

### Telegram username
```
josemcc0705
```

### GitHub username
```
JoseMCCGit
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-unofficial-14-project-matrixx-10-5-1.4673149/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/MotoEdge30Updates/138
```

**Comment by kssrao13882** [comment]
Two things need clarification from ur end:
1) Why are u releasing only vanilla builds? We expect our official maintainers to release both gapps and vanilla. However v r OK with gapps alone being released and vanilla can be optional. But only vanilla won't be fine with us
2) Though u say u been doing roms for 6 months why is it that u joined github just a week back?

**Comment by JoseMCCGit** [comment]
Unofficial release has only vanilla version for see if someone reports a particular bug (because doesn't have major bugs, I tested it), next update will have two versions, gapps and vanilla. And I was creating roms with my local pc seeing how aosp works for increase knowledge, now I have it for official maintanership. Thats why I didn't publish nothing until now

**Comment by RDS-007** [comment]
> Unofficial release has only vanilla version for see if someone reports a particular bug (because doesn't have major bugs, I tested it), next update will have two versions, gapps and vanilla. And I was creating roms with my local pc seeing how aosp works for increase knowledge, now I have it for official maintanership. Thats why I didn't publish nothing until now

ok then. share ur telegram group. Let`s see the response. I checked your device tree and it seems good tho
