### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Tiktodz** [Matrixx-Devices/official_devices#61]
## Name and Codename of the device you want to apply for
```
X00TD
```

## Device Tree sources

```
https://github.com/Tiktodz/android_device_asus_X00TD
https://github.com/Tiktodz/android_kernel_asus_sdm660
https://github.com/Tiktodz/android_kernel_asus_sdm636
https://github.com/Tiktodz/android_vendor_asus_X00TD
```

## What ROM's do you maintain officially/unofficially
```
officially (Project Blaze)
unofficially (Project Matrixx, AwakenOS, Project Sakura, Evolution-X, CrDroid)
```

## How long have you been building Custom ROMs
```
1 years
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
foss.crave.io server
```
## Free trial user or paid user?
```
Free
```

### Telegram username
```
@fakedotkit
```

### GitHub username
```
Tiktodz
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-project-matrixx-10-3-0-unofficial-android-14-u.4673987/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/wizardX00T/964
```

**Comment by kssrao13882** [comment]
For question on what roms u maintain, u mentioned etc. Can u list correct list of all roms u do

**Comment by Tiktodz** [comment]
> For question on what roms u maintain, u mentioned etc. Can u list correct list of all roms u do

I'm sorry, for unofficial build list (Project Matrixx, AwakenOS, Project Sakura, Evolution-X, CrDroid)

**Comment by kssrao13882** [comment]
> > For question on what roms u maintain, u mentioned etc. Can u list correct list of all roms u do
> 
> I'm sorry, for unofficial build list (Project Matrixx, AwakenOS, Project Sakura, Evolution-X, CrDroid)

So totally 6. 1 official and 5 unofficial right? Don't u feel too many roms u r doing?

**Comment by Tiktodz** [comment]
> > > For question on what roms u maintain, u mentioned etc. Can u list correct list of all roms u do
> > 
> > 
> > I'm sorry, for unofficial build list (Project Matrixx, AwakenOS, Project Sakura, Evolution-X, CrDroid)
> 
> So totally 6. 1 official and 5 unofficial right? Don't u feel too many roms u r doing?

yeah right, for me it's too much, but X00TD users always ask me to make a rom so they can experience it, because our device will soon be extinct!

**Comment by kssrao13882** [comment]
> > > > For question on what roms u maintain, u mentioned etc. Can u list correct list of all roms u do
> > > 
> > > 
> > > I'm sorry, for unofficial build list (Project Matrixx, AwakenOS, Project Sakura, Evolution-X, CrDroid)
> > 
> > 
> > So totally 6. 1 official and 5 unofficial right? Don't u feel too many roms u r doing?
> 
> yeah right, for me it's too much, but X00TD users always ask me to make a rom so they can experience it, because our device will soon be extinct!

If that's the case better continue with unofficial Matrixx, we can't take people doing 6 roms as official maintainers
