### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by NerokiStage** [Matrixx-Devices/official_devices#64]
## Name and Codename of the device you want to apply for
```
Samsung Galaxy S20 FE 4G/5G (r8q)
```

## Device Tree sources

```
https://github.com/ata-kaner/android_device_samsung_r8q
https://github.com/ata-kaner/android_kernel_samsung_sm8250
https://github.com/ata-kaner/android_vendor_samsung_sm8250
```

## What ROM's do you maintain officially/unofficially
```
Matrixx
```

## How long have you been building Custom ROMs
```
I started learning in April 2023
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Server
```
## Free trial user or paid user?
```
Free Trial - Always Free
```

### Telegram username
```
@nerokistyle
```

### GitHub username
```
NerokiStage
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-unofficial-encryption-snapdragon-projectmatrixx-for-samsung-galaxy-s20-fe-4g-5g.4675969/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/nerokireleases/3196/16494
```

**Comment by kssrao13882** [comment]
Ur github username is NerokiStage, which has no trees to show ur commits and contributions.

Whose trees are this then?
https://github.com/ata-kaner/

Is it that u don't maintain trees of ur own and just build with other's trees?

**Comment by NerokiStage** [comment]
Until then I use the tree since it is the most stable and I want quality for my builds, but I will bring my own tree yet

**Comment by NerokiStage** [comment]
Besides the fact that it would be extremely difficult for me to contribute a useful commit to the tree, Atakan and the others have made practically all the corrections and additions that actually bring a benefit

**Comment by kssrao13882** [comment]
> Until then I use the tree since it is the most stable and I want quality for my builds, but I will bring my own tree yet.

Better apply later with trees of ur own. The basic minimum thing required for official maintainership is trees by u with commits having proper authorship. A commit does not necessarily mean u write code on ur own. U can even cherry pick useful things from other device trees.
