### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by chuspita** [Matrixx-Devices/official_devices#66]
## Name and Codename of the device you want to apply for
```
Xiaomi redmi note 13 Pro 5G (Garnet)
```

## Device Tree sources

```
https://github.com/chuspita/device_xiaomi_garnet
https://github.com/garnet-random/android_kernel_xiaomi_garnet
https://github.com/chuspita/vendor_xiaomi_garnet
```

## What ROM's do you maintain officially/unofficially
```
Insert here
```

## How long have you been building Custom ROMs
```
Insert here
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Insert here
```
## Free trial user or paid user?
```
Insert here
```

### Telegram username
```
Your Telegram username
```

### GitHub username
```
Your Github username
```

### [MUST] Link to your XDA thread of unofficial build

```
Link to where you have posted your build publically.
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
Link to where you have posted your build publically.
```

**Comment by kssrao13882** [comment]
Incomplete form
