### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by chuspita** [Matrixx-Devices/official_devices#67]
## Name and Codename of the device you want to apply for
```
Xiaomi Redmi Note 13 Pro 5G (Garnet)
```

## Device Tree sources

```
https://github.com/chuspita/device_xiaomi_garnet
https://github.com/garnet-random/android_kernel_xiaomi_garnet
https://github.com/chuspita/vendor_xiaomi_garnet
```

## What ROM's do you maintain officially/unofficially
```
Infinity-X and Afterlife
```

## How long have you been building Custom ROMs
```
About three years
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
locally
```
## Free trial user or paid user?
```
Free trial user
```

### Telegram username
```
franlop77
```

### GitHub username
```
chuspita
```

### [MUST] Link to your XDA thread of unofficial build

```
Link to where you have posted your build publically.
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
Link to where you have posted your build publically.
```

**Comment by kssrao13882** [comment]
U haven't linked the release post. If u haven't built or released, v would highly recommend u to release atleast one unofficial build before applying for official maintainership. Wishing you good luck
