### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ghost** [Matrixx-Devices/official_devices#68]
## Name and Codename of the device you want to apply for
```
Redmi 12C (earth)
```

## Device Tree sources

```
https://github.com/devbx/android_device_xiaomi_earth
https://github.com/devbx/android_kernel_xiaomi_earth
https://github.com/mt6768-dev/proprietary_vendor_xiaomi_earth
https://github.com/mt6768-dev/android_hardware_xiaomi
https://github.com/mt6768-dev/android_device_xiaomi_mt6768-common
```

## What ROM's do you maintain officially/unofficially
```
Evolution X (Unofficially)
```

## How long have you been building Custom ROMs
```
6 month
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Server (crave.io) + Local
```
## Free trial user or paid user?
```
Free Trial
```

### Telegram username
```
devbx0
```

### GitHub username
```
devbx
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-unofficial-project-matrixx-for-redmi-12c-poco-c55.4681195/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
[Telegram](https://t.me/devbx_releases)
```

**Comment by kssrao13882** [comment]
On going through your trees, v feel that u still need some more knowledge of git. Continue doing unofficial for few more months, while learning git properly.
