### ISSUE TITLE
Lucifer

### ISSUE THREAD

**Issue by vidhwabaijan** [Matrixx-Devices/official_devices#7]
## Name and Codename of the device you want to apply for
Mi 10i/Mi 10t Lite/Redmi Note 9 Pro 5G
(gauguin)

## Device Tree sources

```
https://github.com/LuciferEternal/device_xiaomi_gauguin/tree/lineage-21
https://github.com/xiaomi-sm7225/android_kernel_xiaomi_gauguin/tree/lineage-21
https://github.com/LuciferEternal/proprietary_vendor_xiaomi_gauguin/tree/lineage-21
```

## What ROM's do you maintain officially/unofficially
FireDroid(officially)

## How long have you been building Custom ROMs

3 months

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
@LuciferEternal

### Link to your XDA thread of unofficial build
https://xdaforums.com/t/rom-a14-project-matrixx-10-0-beta-unofficial.4645272/

### Link to your unofficial Build Post other than XDA
https://sourceforge.net/u/ssgupta808/profile/
https://t.me/Mankindexternalbuild

**Comment by Mrick343** [comment]
Fill out the form properly.. why the links got messed up

**Comment by Mrick343** [comment]
Plus your trees are also not yours not a single thing is not committed by you

**Comment by vidhwabaijan** [comment]
> Plus your trees are also not yours not a single thing is not committed by you

It's a common tree for our gauguin community developers,well I just forked it

**Comment by Mrick343** [comment]
> > Plus your trees are also not yours not a single thing is not committed by you
> 
> It's a common tree for our gauguin community developers,well I just forked it

This doesn't work like this.. You should gain some more experience before taking official. So for now I'm rejecting your application. Come back later with some real experience and with your own trees

**Comment by vidhwabaijan** [comment]
> > > Plus your trees are also not yours not a single thing is not committed by you
> > 
> > 
> > It's a common tree for our gauguin community developers,well I just forked it
> 
> This doesn't work like this.. You should gain some more experience before taking official. So for now I'm rejecting your application. Come back later with some real experience and with your own trees

Okay I'll
