### ISSUE TITLE
New maintainer for Mi 10 Lite Zoom

### ISSUE THREAD

**Issue by alecchangod** [Matrixx-Devices/official_devices#72]
## Name and Codename of the device you want to apply for
```
Mi 10 Lite Zoom (vangogh)
```

## Device Tree sources

```
https://github.com/alecchangod/android_device_xiaomi_vangogh
https://github.com/alecchangod/android_device_xiaomi_sm7250-common
https://github.com/alecchangod/kernel_xiaomi_sm7250
https://github.com/alecchangod/android_vendor_xiaomi
```

## What ROM's do you maintain officially/unofficially
```
Matrixx official for monet
Lineage and crdroid unofficial
```

## How long have you been building Custom ROMs
```
About 19 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally
```
## Free trial user or paid user?
```
N/A
```

### Telegram username
```
@alecchangod
```

### GitHub username
```
alecchangod
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-unofficial-vangogh-project-matrixx-android-14.4681928/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/mi10litereleases/519
```

**Comment by AAMIRR-ALI** [comment]
accepted welcome to MATRIXX
