### ISSUE TITLE
New maintainer request for Redmi 12 5G (sky)

### ISSUE THREAD

**Issue by alanpdk** [Matrixx-Devices/official_devices#75]
## Name and Codename of the device you want to apply for
```
Redmi 12 5G/Redmi Note 12R/Redmi 12R/POCO M6 PRO 5G
Codename : sky
```

## Device Tree sources

```
https://github.com/alanpdk/device_xiaomi_sky_matrixx
https://github.com/alanpdk/device_xiaomi_sky-kernel
https://github.com/alanpdk/vendor_xiaomi_sky
https://github.com/sm4450-development/device_xiaomi_sky (common DT)
```

## What ROM's do you maintain officially/unofficially
```
DerpFest (Official) & RisingOS (Official)
```

## How long have you been building Custom ROMs
```
5 Months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally
```
## Free trial user or paid user?
```
Local
```

### Telegram username
```
alanpdk
```

### GitHub username
```
alanpdk
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-a14-unofficial-matrixx-v10-6-1-gapps-sky-17-07-2024.4683983/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/Redmi125GChannel/569
https://t.me/Redmi125GChannel/506
https://t.me/Redmi125GChannel/434
https://t.me/Redmi125GChannel/413
https://t.me/Redmi125GChannel/397
https://t.me/Redmi125GChannel/378
```

**Comment by AAMIRR-ALI** [comment]
Greetings from Team Matrixx,

We are happy to inform you that your application for Official Maintainership is accepted
