### ISSUE TITLE
Samsung Galaxy Note 10 5G

### ISSUE THREAD

**Issue by LeDrew2017** [Matrixx-Devices/official_devices#79]
## Name and Codename of the device you want to apply for
```
Samsung Galaxy Note 10 5G (d1x)
```

## Device Tree sources

```
https://github.com/ProjectMatrixx-exynos9820/android_device_samsung_d1x
https://github.com/ProjectMatrixx-exynos9820/android_device_samsung_exynos9820-common
https://github.com/ProjectMatrixx-exynos9820/android_kernel_samsung_exynos9820
https://github.com/ProjectMatrixx-exynos9820/android_vendor_samsung_d1x
https://github.com/ProjectMatrixx-exynos9820/android_vendor_samsung_exynos9820-common
```

## What ROM's do you maintain officially/unofficially
```
Insert here
```

## How long have you been building Custom ROMs
```
Insert here
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Insert here
```
## Free trial user or paid user?
```
Insert here
```

### Telegram username
```
Your Telegram username
```

### GitHub username
```
Your Github username
```

### [MUST] Link to your XDA thread of unofficial build

```
Link to where you have posted your build publically.
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
Link to where you have posted your build publically.
```

**Comment by CuriousNom** [comment]
Greeetings from team Matrixx,
Please fill all the informations properly, all the requirements need to be filled

**Comment by mukesh22584** [comment]
Welcome
