### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AswinOP** [Matrixx-Devices/official_devices#8]
## Name and Codename of the device you want to apply for
```
POCO X4 Pro 5G/Redmi Note 11 Pro+ 5G (VEUX/PEUX)
```

## Device Tree sources

```
https://github.com/aswinop/device_xiaomi_veux
https://github.com/aswinop/kernel_xiaomi_sm6375
https://gitlab.com/aswinop/vendor_xiaomi_veux
```

## What ROM's do you maintain officially/unofficially
```
Matrixx (unofficially), PixelOS (unofficially), DroidX-UI (unofficially).
```

## How long have you been building Custom ROMs
```
2 months 
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally
```
## Free trial user or paid user?
```
I use my PC so not paying / using any free trial.
```

### Telegram username
```
iaswinop
```

### GitHub username
```
aswinop
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-a14-project-matrixx-10-0-beta-2-unofficial.4642613/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA
```
https://sourceforge.net/projects/projectmatrixx-veux/
https://t.me/PocoX4ProUpdates/352
```

**Comment by Mrick343** [comment]
Hey @AswinOP I have checked your trees and seen the reviews from ur users. I am accepting  your application. 

Please contact me on my Telegram for ur invite links and other stuff.
My TG I'd: t.me/Mrick343
