### ISSUE TITLE
New maintainer for beryllium

### ISSUE THREAD

**Issue by Dheeraj3031A** [Matrixx-Devices/official_devices#84]
## Name and Codename of the device you want to apply for
```
Pocophone F1 (beryllium)
```

## Device Tree sources

```
https://github.com/Dheeraj3031A/android_device_xiaomi_beryllium
https://github.com/Dheeraj3031A/kernel_xiaomi_beryllium
https://github.com/Dheeraj3031A/proprietary_vendor_xiaomi_beryllium
```

## What ROM's do you maintain officially/unofficially
```
Project Matrixx (Unofficial)
```

## How long have you been building Custom ROMs
```
1 year
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally
```
## Free trial user or paid user?
```
Local build
```

### Telegram username
```
NotDheeraj06
```

### GitHub username
```
Dheeraj3031A
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/a14-rom-project-matrixx-v10-7-1-beryllium-unofficial.4691131/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/NotDheeraj06_Builds/69
https://sourceforge.net/projects/beryllium-roms/files/Matrixx-v10.7.1-Community-beryllium-20240818/
```

**Comment by CuriousNom** [comment]
Greetings from team Matrixx,
Kindly check the vendor repo, link is invalid

**Comment by Dheeraj3031A** [comment]
It has been fixed

**Comment by CuriousNom** [comment]
Greetings, 
Your application is accepted
