### ISSUE TITLE
New maintainer for a71

### ISSUE THREAD

**Issue by onesmiledx** [Matrixx-Devices/official_devices#86]
## Name and Codename of the device you want to apply for
```
Samsung Galaxy A71 4G
```

## Device Tree sources

```
https://github.com/matrixx-a71/android_device_samsung_a71
https://github.com/matrixx-a71/android_device_samsung_a71-common
https://github.com/matrixx-a71/android_kernel_samsung_a71
https://github.com/matrixx-a71/android_vendor_samsung_a71
https://github.com/matrixx-a71/android_vendor_samsung_a71-common
```

## What ROM's do you maintain officially/unofficially
```
RisingOS, DroidX, PixelOS, Alphadroid, Derpfest and EvolutionX (Unofficially)
```

## How long have you been building Custom ROMs
```
6 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Microsoft Azure
```
## Free trial user or paid user?
```
Free trial
```

### Telegram username
```
whystarlix
```

### GitHub username
```
onesmiledx
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-0-unofficial-stable-20240911-project-matrixx-10-8-0-for-samsung-galaxy-a71-4g-ss-ds.4692139/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/Haky86Chat/8505
```

**Comment by CuriousNom** [comment]
Hi,
How will u maintain 6 roms unofficialy and matrixx officialy?

**Comment by onesmiledx** [comment]
hi. i'm building that using microsoft azure right now, but after end free tier i'll build that on Crave, i'll build that roms every months cuz now i have a server, for me building a rom is hobby.

**Comment by CuriousNom** [comment]
And u also dont have enough contributions to the trees, just have bringup it

**Comment by onesmiledx** [comment]
sorry, i just idk what contribute, i created device tree for samsung galaxy a10s but idk what to do for samsung galaxy a71 cuz here is only 1 bug (VoLTE which not fixing)

**Comment by CuriousNom** [comment]
show me your work of a10s

**Comment by onesmiledx** [comment]
https://github.com/samsung-mt6765-devs (yeah, i know that trees look so funny but it working)

**Comment by CuriousNom** [comment]
show me the roms u have booted and posted

**Comment by onesmiledx** [comment]
> show me the roms u have booted and posted

https://t.me/a107x/1/147648

**Comment by CuriousNom** [comment]
Greetings,

Thank you for your application. Unfortunately, we cannot move forward with it at this time. It’s crucial to continue contributing to the current device you are working on. We recommend that you maintain Matrixx unofficially for a bit longer and consider reapplying later.
