### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by JigenxOhtsusuki** [Matrixx-Devices/official_devices#88]
## Name and Codename of the device you want to apply for
```
Realme 5/5i/5s (r5x)
```

## Device Tree sources

```
https://github.com/JigenxOhtsusuki/android_device_realme_r5x
https://github.com/Amritorock/kernel_realme_sm6125
https://github.com/Amritorock/vendor_realme_r5x
```

## What ROM's do you maintain officially/unofficially
```
no officially maintained roms, unofficially i built risingOS, crDroid, AlphaDroid, InfinityX, /e/OS, CalyxOS, Matrixx OS
```

## How long have you been building Custom ROMs
```
5 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally
```
## Free trial user or paid user?
```
N/A
```

### Telegram username
```
@jigenxohtsusuki
```

### GitHub username
```
JigenxOhtsusuki
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-a14-project-matrixx-10-8-0-unofficial.4694487/
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/jigen_builds/19
```
### sorry forgot to mention before
```
boot animation resolution is exception coz our device screen resolution is 720p
```

**Comment by kshitij-vk** [comment]
Greetings from Team Matrixx!
I saw your trees but I did not find any notable contribution or even a commit from your side. Solely having trees does not entitle one to get official support. We must understand that you are capable enough to work on device resources and handle build errors, bugs and basic troubleshooting.

So for now I will close the request. Surely you can apply once you have notable work on your device resources with which we can evaluate something out of it.
