### ISSUE TITLE
New maintainer for stone 

### ISSUE THREAD

**Issue by Nomishaw21** [Matrixx-Devices/official_devices#89]
## Name and Codename of the device you want to apply for
```
Stone
```

## Device Tree sources

```
https://github.com/Nomishaw21/device_xiaomi_stone
https://github.com/Nomishaw21/device_xiaomi_stone
https://github.com/Nomishaw21/vendor_xiaomi_stone
```

## What ROM's do you maintain officially/unofficially
```
Official - blaze and halcyon
```

## How long have you been building Custom ROMs
```
1 year+
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
GCP
```
## Free trial user or paid user?
```
Free trial
```

### Telegram username
```
@Nomishaw
```

### GitHub username
```
Nomishaw21
```

### [MUST] Link to your XDA thread of unofficial build

```
not yet.
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/stone_updates/86
```

**Comment by Arijit78** [comment]
Hi,
Your build is too much old which you provided.Kindly build and share latest link.

Thank You

**Comment by Nomishaw21** [comment]
Ok

**Comment by Nomishaw21** [comment]
https://t.me/moonstone_sunstone/218318

@Arijit78 new link

**Comment by Arijit78** [comment]
> https://t.me/moonstone_sunstone/218318
> 
> @Arijit78 new link

Ok.Where is your device kernel source.You must need to provide it

**Comment by Nomishaw21** [comment]
https://github.com/Nomishaw21/device_xiaomi_stone-kernel

Lmao forgot to add -kernel
