### ISSUE TITLE
Applying for maintainership for Galaxy A10

### ISSUE THREAD

**Issue by Masood-J** [Matrixx-Devices/official_devices#90]
## Name and Codename of the device you want to apply for
```
Galaxy A10 (a10)
```

## Device Tree sources

```
https://github.com/eurekadevelopment/android_device_samsung_exynos7885 #branch (android-14)
https://github.com/eurekadevelopment/Eureka-Kernel-Exynos7885-Q-R-S #branch (R15_rom)
https://github.com/eurekadevelopment/android_vendor_samsung_exynos7885 #branch (android-14)
```

## What ROM's do you maintain officially/unofficially
```
Crdroid(officially)
```

## How long have you been building Custom ROMs
```
1.5 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
I used foss.crave.io for building
```
## Free trial user or paid user?
```
Its a free server
```

### Telegram username
```
@masood_zen
```

### GitHub username
```
Masood-J
```

### [MUST] Link to your XDA thread of unofficial build

```
[Link to where you have posted your build publically.](https://xdaforums.com/t/rom-14-0-unofficial-project-matrixx-v10-8-1-galaxy-a10-qpr3.4696112/)
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
Link to where you have posted your build publically.
```

**Comment by CuriousNom** [comment]
Greetings from Team Matrixx!
Your trees don't meet out the expectation of being officially supported. Kindly learn git stuff and fix ur commit history.
After gaining some experience, you can reapply
