### ISSUE TITLE
new maintainer for munch

### ISSUE THREAD

**Issue by rik-x777** [Matrixx-Devices/official_devices#91]
## Name and Codename of the device you want to apply for
```
poco f4 (munch)
```

## Device Tree sources

```
https://github.com/rik-x777/android_device_xiaomi_munch.git
https://github.com/rik-x777/android_device_xiaomi_sm8250-common.git
https://github.com/AnkitSavani111/android_kernel_xiaomi_sm8250.git
https://github.com/TheMuppets/proprietary_vendor_xiaomi_munch.git
https://github.com/TheMuppets/proprietary_vendor_xiaomi_sm8250-common.git
```

## What ROM's do you maintain officially/unofficially
```
crdroid officially and rising os unofficially.
```

## How long have you been building Custom ROMs
```
2 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
server. crave.io
```
## Free trial user or paid user?
```
free
```

### Telegram username
@rik_x290

### Telegram username
Rik

### GitHub username
rik-x777

### [MUST] Link to your XDA thread of unofficial build
https://xdaforums.com/t/rom-android-14-qpr3-project-matrixx-10-9-0-community-munch.4698406/#post-89763944

### [MUST] Link to your unofficial Matrixx Build Post other than XDA
https://t.me/PocoF4updates/1203

**Comment by CuriousNom** [comment]
Greetings from Team Matrixx!
Unfortunately your trees don't meet out the expectation of being officially supported. Kindly learn git stuff and fix ur commit history.

After gaining some experience, you can reapply, 
Thanx for showing interest in our project!

**Comment by rik-x777** [comment]
@CuriousNom what exactly doesn't meet your expectation?

**Comment by CuriousNom** [comment]
Thank you for your message. The main reasons for the rejection were the lack of meaningful changes in all the device-related trees and improper formatting of your commit messages. It’s crucial to make substantial improvements to the trees and ensure that your commit messages follow the proper structure for clarity and consistency. Once these are addressed, your submission will be much stronger.

**Comment by rik-x777** [comment]
@CuriousNom https://github.com/rik-x777/device/tree/matrixx
https://github.com/rik-x777/common

these will do?
