### ISSUE TITLE
New maintainer for sapphire/sapphiren

### ISSUE THREAD

**Issue by ReStranger** [Matrixx-Devices/official_devices#94]
## Name and Codename of the device you want to apply for
```
sapphire/sapphiren
```

## Device Tree sources

```
https://github.com/sm6225-sapphire-oss/device_xiaomi_sapphire
https://github.com/sm6225-sapphire-oss/device_xiaomi_sapphire-kernel
https://github.com/sm6225-sapphire-oss/vendor_xiaomi_sapphire
```

## What ROM's do you maintain officially/unofficially
```
Only matrixx
```

## How long have you been building Custom ROMs
```
3 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
I build in my home pc
```
## Free trial user or paid user?
```
free, because this is my pc :D
```

### Telegram username
```
ReStranger
```

### GitHub username
```
ReStranger
```

### [MUST] Link to your XDA thread of unofficial build

```
[XDA](https://xdaforums.com/t/rom-14-sapphire-project-matrixx-10-9-1-unofficial.4701480/)
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
[Telegram](https://t.me/re_update/113)
```

**Comment by CuriousNom** [comment]
Greetings from Team Matrixx!
Unfortunately your trees don't meet out the expectation of being officially supported. Kindly learn git stuff and fix ur commit history. 

After gaining some experience, you can reapply,
Also we are not accepting any new maintainer till A15 release of our project……
Thanx for showing interest in our project!
