### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ZorEl212** [Matrixx-Devices/official_devices#95]
## Name and Codename of the device you want to apply for
```
Redmi Note 8/8T (ginkgo/willow)
```

## Device Tree sources

```
https://github.com/ZorEl212/android_device_xiaomi_ginkgo-retrofit
https://github.com/ZorEl212/android_kernel_xiaomi_ginkgo
https://github.com/ZorEl212/proprietary_vendor_xiaomi_ginkgo
```

## What ROM's do you maintain officially/unofficially
```
ArrowOS Extended
```

## How long have you been building Custom ROMs
```
Almost 5 years (since 2021)
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
I build locally sometimes, for pc health concerns I use paid servers
```
## Free trial user or paid user?
```
Paid user
```

### Telegram username
```
@k_y_c_i_i_9_1
```

### GitHub username
```
ZorEl212
```

### [MUST] Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-a14-ginkgo-willow-unofficial-project-matrixx-v-10-9-1-17-10-24.4703451
```

### [MUST] Link to your unofficial Matrixx Build Post other than XDA

```
https://t.me/GinkgoUpdates/3827
https://t.me/rogerbuilds/810
https://t.me/redminote8update/6554
```

**Comment by CuriousNom** [comment]
Greetings from Team Matrixx!
We are currently not accepting maintainers till the release of our Project Matrixx based on A15, kindly wait for the new version release, build, test, boot and reapply later. 

Thank You for showing interest in our Project!
